version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  my-vertx-app:
    image: vertx-assignment-docker
    build:
      context: .
    container_name: my-vertx-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin

